proxy:
  title: CIML Shiny Server
  logo-url: http://www.ciml.univ-mrs.fr/themes/custom/ciml_theme/logo.svg
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: simple
  admin-groups: admin
  container-log-path: /tmp/container-logs
  
  
  
  # ########################################
  # Users configuration
  # #########################################
  
  # Example: 'simple' authentication configuration
  
  users:
  - name: admin
    password: 'adminpassword'
    groups: admin

  - name: shiva
    password: 'userpassowrd'
    groups: scientists

  # ########################################
  # Docker configuration
  # #########################################
  docker:
    cert-path: /home/none
    url: http://localhost:2375
    port-range-start: 20000
  specs:
  - id: ShIVA_1.1
    display-name: Shiva version 1.1
    container-cmd: ["R", "-e", "shiny::runApp('/root/Shiva', host='0.0.0.0', port=3838)"]
    container-image: cb2m/shiva:1.1
    container-volumes: ["/shivaOutput/shiva_seurat4/#{proxy.userId}:/root/Shiva/Output"]
    
logging:
  file:
    /etc/shinyproxy/shinyproxy.log
  level:
    DEBUG
